In [67]:
import pandas as pd
import numpy as np

In [68]:
life=pd.read_csv('/Users/vaishnaviuttarkar/Life Expectany/Life_Expectancy_Model/CleanedLifeExpectancy.csv')

In [69]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Unnamed: 0                    2938 non-null   int64  
 1   Country                       2938 non-null   object 
 2   Year                          2938 non-null   int64  
 3   Status                        2938 non-null   object 
 4   Lifeexpectancy                2938 non-null   float64
 5   AdultMortality                2938 non-null   int64  
 6   infantdeaths                  2938 non-null   int64  
 7   Alcohol                       2938 non-null   float64
 8   percentageexpenditure         2938 non-null   float64
 9   HepatitisB                    2938 non-null   int64  
 10  Measles                       2938 non-null   int64  
 11  BMI                           2938 non-null   float64
 12  under-fivedeaths              2938 non-null   int64  
 13  Pol

In [70]:
life.drop('Unnamed: 0',inplace=True,axis=1)

In [71]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Country                       2938 non-null   object 
 1   Year                          2938 non-null   int64  
 2   Status                        2938 non-null   object 
 3   Lifeexpectancy                2938 non-null   float64
 4   AdultMortality                2938 non-null   int64  
 5   infantdeaths                  2938 non-null   int64  
 6   Alcohol                       2938 non-null   float64
 7   percentageexpenditure         2938 non-null   float64
 8   HepatitisB                    2938 non-null   int64  
 9   Measles                       2938 non-null   int64  
 10  BMI                           2938 non-null   float64
 11  under-fivedeaths              2938 non-null   int64  
 12  Polio                         2938 non-null   int64  
 13  Tot

Label Encoding

In [72]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
a= life.select_dtypes(include='object').columns
for i in a:
    life[i] = le.fit_transform(life[i])

In [73]:
life.dtypes

Country                           int64
Year                              int64
Status                            int64
Lifeexpectancy                  float64
AdultMortality                    int64
infantdeaths                      int64
Alcohol                         float64
percentageexpenditure           float64
HepatitisB                        int64
Measles                           int64
BMI                             float64
under-fivedeaths                  int64
Polio                             int64
Totalexpenditure                float64
Diphtheria                        int64
HIV/AIDS                        float64
GDP                               int64
Population                        int64
thinness1-19years               float64
thinness5-9years                float64
Incomecompositionofresources    float64
Schooling                       float64
dtype: object

Separating dependent and independent variables

In [74]:
life.shape

(2938, 22)

In [75]:
X=life.drop(columns='Lifeexpectancy')
y=life['Lifeexpectancy']

Performing train-test split


In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

Trying out several algorithms

In [78]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt

In [79]:
alg=[LinearRegression(),Ridge(),Lasso(),DecisionTreeRegressor(),RandomForestRegressor(),XGBRegressor(),KNeighborsRegressor()]

names=['linearregression','ridgeregression','lassoregression','decisiontreeregressor','randomforestregressor','xgboostregressor','kneighborsregressor']

In [80]:
l1=[]
for i in alg:
    model=i
    model.fit(X_train,y_train)
    y_hat=model.predict(X_test)
    mse=mean_squared_error(y_test,y_hat)
    rmse=sqrt(mse)
    l1.append(rmse)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:212: LinAlgWarning: Ill-conditioned matrix (rcond=5.23045e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.088e+04, tolerance: 2.145e+01
  model = cd_fast.enet_coordinate_descent(


In [81]:
eval=pd.DataFrame({'Model':names,
                  'RMSE':l1})

In [82]:
eval

Model      RMSE
0       linearregression  3.889173
1        ridgeregression  3.886908
2        lassoregression  3.964915
3  decisiontreeregressor  2.659397
4  randomforestregressor  1.653958
5       xgboostregressor  1.777019
6    kneighborsregressor  9.156520

Conclusion: Random forest gives the best accuracy

In [83]:
from sklearn.ensemble import RandomForestRegressor

rr=RandomForestRegressor ()

rr.fit(X_train,y_train)

y_hat=rr.predict(X_test)

In [84]:
y_hat

array([72.923     , 75.994     , 74.929     , 76.127     , 52.696     ,
       51.634     , 66.324     , 73.943     , 76.647     , 55.955     ,
       52.064     , 52.093     , 57.221     , 74.129     , 69.57249863,
       61.868     , 58.03      , 78.998     , 70.182     , 79.036     ,
       80.964     , 84.398     , 72.607     , 69.03324932, 71.39224658,
       67.961     , 55.872     , 65.291     , 82.125     , 74.019     ,
       67.474     , 74.254     , 74.122     , 71.825     , 78.774     ,
       48.876     , 60.609     , 72.40924932, 63.748     , 73.693     ,
       54.614     , 60.585     , 75.425     , 81.304     , 76.657     ,
       49.84      , 79.893     , 74.699     , 60.692     , 71.716     ,
       53.992     , 70.943     , 82.636     , 80.931     , 74.435     ,
       58.053     , 72.995     , 75.273     , 63.247     , 69.468     ,
       78.311     , 54.534     , 74.373     , 72.379     , 53.118     ,
       54.071     , 52.467     , 76.901     , 58.839     , 72.08

In [85]:
from sklearn.metrics import r2_score
r2_score(y_hat,y_test)

0.9677318025348988

In [86]:
life.columns

Index(['Country', 'Year', 'Status', 'Lifeexpectancy', 'AdultMortality',
       'infantdeaths', 'Alcohol', 'percentageexpenditure', 'HepatitisB',
       'Measles', 'BMI', 'under-fivedeaths', 'Polio', 'Totalexpenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness1-19years',
       'thinness5-9years', 'Incomecompositionofresources', 'Schooling'],
      dtype='object')

In [87]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Country                       2938 non-null   int64  
 1   Year                          2938 non-null   int64  
 2   Status                        2938 non-null   int64  
 3   Lifeexpectancy                2938 non-null   float64
 4   AdultMortality                2938 non-null   int64  
 5   infantdeaths                  2938 non-null   int64  
 6   Alcohol                       2938 non-null   float64
 7   percentageexpenditure         2938 non-null   float64
 8   HepatitisB                    2938 non-null   int64  
 9   Measles                       2938 non-null   int64  
 10  BMI                           2938 non-null   float64
 11  under-fivedeaths              2938 non-null   int64  
 12  Polio                         2938 non-null   int64  
 13  Tot

In [88]:
inputfeatures=[15,2016,1,100,1000,3.4,56.6,80,8000,19.1,800,90,5.9,90,0.3,1500.1,13245172,20.1,26.5,0.643,11.1]

In [89]:
#input_features=sc.fit_transform([inputfeatures])

In [90]:
#rr.predict(input_features)

In [91]:
rr.predict([[20,2017,0,100,1000,4.4,57.6,80,9000,18.1,700,80,6.9,80,0.4,2500.1,132451723,21.1,25.5,0.463,12.1]])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([66.62])

- Testing training data as an input

Expected = 79.7

In [92]:
# Iceland-2000 (79.7)
inputfeatures=[75,2000,0,74,0,6.17,5809.122,80,0,54.2,0,98,9.28,98,0.1,74,28125,1,0.9,0.847,16.8]

rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([79.737])

In [93]:
# Iraq-2015 (68.9)
inputfeatures=[79,2015,1,182,32,4.602861,0,56,1433,59.1,38,63,5.93819,58,0.1,182,36115649,5.3,5.1,0.649,10.1]
#input_features=sc.fit_transform([inputfeatures])
rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([70.15824932])

In [94]:
# Greece-2014 (88)
inputfeatures=[66,2014,1,73,0,7.53,2163.043,96,1,66,0,99,8.8,99,0.1,73,1892413,0.8,0.7,0.862,17.2]

rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([86.07])

In [95]:
# Cyprus-2015 (85)
inputfeatures=[43,2015,0,52,0,4.602861,0,97,0,6.3,0,97,5.93819,97,0.1,52,116985,1,1,0.854,14.3]

rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([83.675])

In [96]:
# Hungary-2011 (74.8)
inputfeatures=[79,2015,1,182,32,4.602861,0,56,1433,59.1,38,63,5.93819,58,0.1,182,36115649,5.3,5.1,0.649,10.1]

rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([70.15824932])

In [97]:
# Latvia-2007 (78)
inputfeatures=[92,2007,0,221,0,12.12,170.9884,91,0,57.7,0,94,7.1,94,0.1,221,22325,2.4,2.4,0.814,16.2]

rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([73.574])

In [98]:
# Malawi-2010 (52.9)
inputfeatures=[100,2010,1,462,35,1.08,9.728005,93,118712,17.6,54,86,1.5,93,13.7,462,1516795,6.8,6.7,0.43,10.2]

rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([52.501])

In [99]:
# Nepal-2002 (63.1)
inputfeatures=[118,2002,1,238,40,0.19,23.18395,80,6749,12.4,54,72,5.6,72,0.1,238,24566342,18.2,18.8,0.447,8.6]

rr.predict([inputfeatures])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([63.027])

In [100]:
# # Nepal-2002 (63.1)
# inputfeatures=[118,2002,1,238,40,0.19,23.18395,80,6749,12.4,54,72,5.6,72,0.1,238,24566342,18.2,18.8,0.447,8.6]
# input_features=sc.fit_transform([inputfeatures])
# rr.predict(input_features)

In [101]:
import pickle

In [102]:
pickle.dump(rr,open('RandomRegressionModel.pkl','wb'))