In [1]:
import pandas as pd
import numpy as np

In [2]:
life=pd.read_csv('/Users/vaishnaviuttarkar/Life Expectany/Life_Expectancy_Model/CleanedLifeExpectancy.csv')

In [3]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Unnamed: 0                    2938 non-null   int64  
 1   Country                       2938 non-null   object 
 2   Year                          2938 non-null   int64  
 3   Status                        2938 non-null   object 
 4   Lifeexpectancy                2938 non-null   float64
 5   AdultMortality                2938 non-null   int64  
 6   infantdeaths                  2938 non-null   int64  
 7   Alcohol                       2938 non-null   float64
 8   percentageexpenditure         2938 non-null   float64
 9   HepatitisB                    2938 non-null   int64  
 10  Measles                       2938 non-null   int64  
 11  BMI                           2938 non-null   float64
 12  under-fivedeaths              2938 non-null   int64  
 13  Pol

In [4]:
life.drop('Unnamed: 0',inplace=True,axis=1)

In [5]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Country                       2938 non-null   object 
 1   Year                          2938 non-null   int64  
 2   Status                        2938 non-null   object 
 3   Lifeexpectancy                2938 non-null   float64
 4   AdultMortality                2938 non-null   int64  
 5   infantdeaths                  2938 non-null   int64  
 6   Alcohol                       2938 non-null   float64
 7   percentageexpenditure         2938 non-null   float64
 8   HepatitisB                    2938 non-null   int64  
 9   Measles                       2938 non-null   int64  
 10  BMI                           2938 non-null   float64
 11  under-fivedeaths              2938 non-null   int64  
 12  Polio                         2938 non-null   int64  
 13  Tot

Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
a= life.select_dtypes(include='object').columns
for i in a:
    life[i] = le.fit_transform(life[i])

In [7]:
life.dtypes

Country                           int64
Year                              int64
Status                            int64
Lifeexpectancy                  float64
AdultMortality                    int64
infantdeaths                      int64
Alcohol                         float64
percentageexpenditure           float64
HepatitisB                        int64
Measles                           int64
BMI                             float64
under-fivedeaths                  int64
Polio                             int64
Totalexpenditure                float64
Diphtheria                        int64
HIV/AIDS                        float64
GDP                               int64
Population                        int64
thinness1-19years               float64
thinness5-9years                float64
Incomecompositionofresources    float64
Schooling                       float64
dtype: object

Separating dependent and independent variables

In [8]:
life.shape

(2938, 22)

In [9]:
X=life.drop(columns='Lifeexpectancy')
y=life['Lifeexpectancy']

Performing train-test split


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

Feature scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

Trying out several algorithms

In [12]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt

In [13]:
alg=[LinearRegression(),Ridge(),Lasso(),DecisionTreeRegressor(),RandomForestRegressor(),XGBRegressor(),KNeighborsRegressor()]

names=['linearregression','ridgeregression','lassoregression','decisiontreeregressor','randomforestregressor','xgboostregressor','kneighborsregressor']

In [14]:
l1=[]
for i in alg:
    model=i
    model.fit(X_train,y_train)
    y_hat=model.predict(X_test)
    mse=mean_squared_error(y_test,y_hat)
    rmse=sqrt(mse)
    l1.append(rmse)

In [15]:
eval=pd.DataFrame({'Model':names,
                  'RMSE':l1})

In [16]:
eval

Model      RMSE
0       linearregression  3.924507
1        ridgeregression  3.932514
2        lassoregression  4.350379
3  decisiontreeregressor  3.045138
4  randomforestregressor  1.858330
5       xgboostregressor  2.026021
6    kneighborsregressor  2.510073

Conclusion: Random forest gives the best accuracy

In [17]:
from sklearn.ensemble import RandomForestRegressor

rr=RandomForestRegressor ()

rr.fit(X_train,y_train)

y_hat=rr.predict(X_test)

In [18]:
y_hat

array([73.326     , 76.016     , 74.507     , 76.563     , 51.403     ,
       52.596     , 65.671     , 73.97      , 76.582     , 54.715     ,
       52.388     , 54.76      , 58.308     , 74.908     , 70.24474795,
       61.873     , 58.071     , 79.176     , 69.103     , 79.324     ,
       80.786     , 83.461     , 71.48424932, 68.56424932, 71.27799454,
       67.705     , 56.706     , 65.485     , 82.298     , 73.61624932,
       67.21      , 74.392     , 74.056     , 71.853     , 78.796     ,
       49.095     , 59.188     , 73.41924658, 64.089     , 73.982     ,
       55.164     , 60.571     , 75.643     , 80.964     , 76.392     ,
       49.911     , 80.392     , 75.331     , 60.786     , 71.569     ,
       55.688     , 71.312     , 81.696     , 79.003     , 74.704     ,
       57.025     , 72.767     , 75.111     , 64.149     , 70.23      ,
       77.702     , 54.791     , 74.417     , 71.996     , 53.731     ,
       54.292     , 52.718     , 76.941     , 58.369     , 71.81

In [19]:
from sklearn.metrics import r2_score
r2_score(y_hat,y_test)

0.9558198503230277

In [20]:
life.columns

Index(['Country', 'Year', 'Status', 'Lifeexpectancy', 'AdultMortality',
       'infantdeaths', 'Alcohol', 'percentageexpenditure', 'HepatitisB',
       'Measles', 'BMI', 'under-fivedeaths', 'Polio', 'Totalexpenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness1-19years',
       'thinness5-9years', 'Incomecompositionofresources', 'Schooling'],
      dtype='object')

In [28]:
rr.predict([[15,2016,1,100,1000,3.4,56.6,80,8000,19.1,800,90,5.9,90,0.3,1500.1,13245172,20.1,26.5,0.643,11.1]])

array([48.245])

In [30]:
rr.predict([[20,2017,0,100,1000,4.4,57.6,80,9000,18.1,700,80,6.9,80,0.4,2500.1,132451723,21.1,25.5,0.463,12.1]])

array([48.497])