In [36]:
import pandas as pd
import numpy as np

In [37]:
life=pd.read_csv('/Users/vaishnaviuttarkar/Life Expectany/Life_Expectancy_Model/CleanedLifeExpectancy.csv')

In [38]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Unnamed: 0                    2938 non-null   int64  
 1   Country                       2938 non-null   object 
 2   Year                          2938 non-null   int64  
 3   Status                        2938 non-null   object 
 4   Lifeexpectancy                2938 non-null   float64
 5   AdultMortality                2938 non-null   int64  
 6   infantdeaths                  2938 non-null   int64  
 7   Alcohol                       2938 non-null   float64
 8   percentageexpenditure         2938 non-null   float64
 9   HepatitisB                    2938 non-null   int64  
 10  Measles                       2938 non-null   int64  
 11  BMI                           2938 non-null   float64
 12  under-fivedeaths              2938 non-null   int64  
 13  Pol

In [39]:
life.drop('Unnamed: 0',inplace=True,axis=1)

In [40]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Country                       2938 non-null   object 
 1   Year                          2938 non-null   int64  
 2   Status                        2938 non-null   object 
 3   Lifeexpectancy                2938 non-null   float64
 4   AdultMortality                2938 non-null   int64  
 5   infantdeaths                  2938 non-null   int64  
 6   Alcohol                       2938 non-null   float64
 7   percentageexpenditure         2938 non-null   float64
 8   HepatitisB                    2938 non-null   int64  
 9   Measles                       2938 non-null   int64  
 10  BMI                           2938 non-null   float64
 11  under-fivedeaths              2938 non-null   int64  
 12  Polio                         2938 non-null   int64  
 13  Tot

Label Encoding

In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
a= life.select_dtypes(include='object').columns
for i in a:
    life[i] = le.fit_transform(life[i])

In [42]:
life.dtypes

Country                           int64
Year                              int64
Status                            int64
Lifeexpectancy                  float64
AdultMortality                    int64
infantdeaths                      int64
Alcohol                         float64
percentageexpenditure           float64
HepatitisB                        int64
Measles                           int64
BMI                             float64
under-fivedeaths                  int64
Polio                             int64
Totalexpenditure                float64
Diphtheria                        int64
HIV/AIDS                        float64
GDP                               int64
Population                        int64
thinness1-19years               float64
thinness5-9years                float64
Incomecompositionofresources    float64
Schooling                       float64
dtype: object

Separating dependent and independent variables

In [43]:
life.shape

(2938, 22)

In [44]:
X=life.drop(columns='Lifeexpectancy')
y=life['Lifeexpectancy']

Performing train-test split


In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

Feature scaling

In [46]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

Trying out several algorithms

In [47]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt

In [48]:
alg=[LinearRegression(),Ridge(),Lasso(),DecisionTreeRegressor(),RandomForestRegressor(),XGBRegressor(),KNeighborsRegressor()]

names=['linearregression','ridgeregression','lassoregression','decisiontreeregressor','randomforestregressor','xgboostregressor','kneighborsregressor']

In [49]:
l1=[]
for i in alg:
    model=i
    model.fit(X_train,y_train)
    y_hat=model.predict(X_test)
    mse=mean_squared_error(y_test,y_hat)
    rmse=sqrt(mse)
    l1.append(rmse)

In [50]:
eval=pd.DataFrame({'Model':names,
                  'RMSE':l1})

In [51]:
eval

Model      RMSE
0       linearregression  3.924507
1        ridgeregression  3.932514
2        lassoregression  4.350379
3  decisiontreeregressor  3.068850
4  randomforestregressor  1.846823
5       xgboostregressor  2.026021
6    kneighborsregressor  2.510073

Conclusion: Random forest gives the best accuracy

In [52]:
from sklearn.ensemble import RandomForestRegressor

rr=RandomForestRegressor ()

rr.fit(X_train,y_train)

y_hat=rr.predict(X_test)

In [53]:
y_hat

array([73.147     , 75.913     , 74.658     , 76.435     , 52.352     ,
       51.965     , 65.427     , 74.073     , 76.522     , 54.534     ,
       52.07      , 55.157     , 58.317     , 74.814     , 70.31574795,
       62.085     , 58.051     , 79.234     , 69.246     , 78.988     ,
       81.        , 84.348     , 71.80774795, 68.783     , 71.29399727,
       67.268     , 55.342     , 65.397     , 82.61      , 74.19649863,
       67.442     , 73.91      , 74.097     , 71.722     , 78.573     ,
       48.887     , 59.281     , 72.91074522, 64.111     , 73.895     ,
       55.017     , 60.818     , 75.615     , 80.96      , 76.38      ,
       50.469     , 80.293     , 75.188     , 59.899     , 72.115     ,
       55.888     , 71.002     , 81.845     , 79.366     , 74.883     ,
       57.636     , 72.852     , 75.187     , 64.427     , 70.726     ,
       77.413     , 54.777     , 74.643     , 72.651     , 53.34      ,
       54.013     , 52.123     , 76.971     , 58.584     , 72.49

In [54]:
from sklearn.metrics import r2_score
r2_score(y_hat,y_test)

0.9578055032310973

In [55]:
life.columns

Index(['Country', 'Year', 'Status', 'Lifeexpectancy', 'AdultMortality',
       'infantdeaths', 'Alcohol', 'percentageexpenditure', 'HepatitisB',
       'Measles', 'BMI', 'under-fivedeaths', 'Polio', 'Totalexpenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness1-19years',
       'thinness5-9years', 'Incomecompositionofresources', 'Schooling'],
      dtype='object')

In [56]:
rr.predict([[15,2016,1,100,1000,3.4,56.6,80,8000,19.1,800,90,5.9,90,0.3,1500.1,13245172,20.1,26.5,0.643,11.1]])

array([48.849])

In [57]:
rr.predict([[20,2017,0,100,1000,4.4,57.6,80,9000,18.1,700,80,6.9,80,0.4,2500.1,132451723,21.1,25.5,0.463,12.1]])

array([48.894])

- Testing training data as an input

Expected = 79.7

In [58]:
# Iceland-2000 (79.7)
rr.predict([[75,2000,0,74,0,6.17,5809.122,80,0,54.2,0,98,9.28,98,0.1,74,28125,1,0.9,0.847,16.8]])

array([49.822])

In [59]:
# Iraq-2015 (68.9)
rr.predict([[79,2015,1,182,32,4.602861,0,56,1433,59.1,38,63,5.93819,58,0.1,182,36115649,5.3,5.1,0.649,10.1]])

array([49.829])

In [60]:
# Greece-2014 (88)
rr.predict([[66,2014,1,73,0,7.53,2163.043,96,1,66,0,99,8.8,99,0.1,73,1892413,0.8,0.7,0.862,17.2]])

array([49.788])

In [62]:
# Cyprus-2015 (85)
rr.predict([[43,2015,0,52,0,4.602861,0,97,0,6.3,0,97,5.93819,97,0.1,52,116985,1,1,0.854,14.3]])

array([49.822])

In [63]:
# Hungary-2011 (74.8)
rr.predict([[74,2011,0,15,0,11.51,17.82122,80,5,62.4,1,99,7.84,99,0.1,15,9971727,1.7,1.7,0.821,15.4]])

array([49.718])

In [64]:
# Latvia-2007 (78)
rr.predict([[92,2007,0,221,0,12.12,170.9884,91,0,57.7,0,94,7.1,94,0.1,221,22325,2.4,2.4,0.814,16.2]])

array([50.008])

In [65]:
# Malawi-2010 (52.9)
rr.predict([[100,2010,1,462,35,1.08,9.728005,93,118712,17.6,54,86,1.5,93,13.7,462,1516795,6.8,6.7,0.43,10.2]])

array([49.952])

In [66]:
# Nepal-2002 (63.1)
rr.predict([[118,2002,1,238,40,0.19,23.18395,80,6749,12.4,54,72,5.6,72,0.1,238,24566342,18.2,18.8,0.447,8.6]])

array([49.837])